#
- name: 'apm clean : delete unused packages in node_modules'
  command: apm clean
  changed_when: false

- name: apm upgrade all packages
  command: 'apm upgrade --no-confirm'
  changed_when: false
  register: atom_upgrade_result

- debug: var=atom_upgrade_result

# - name: install brew apps
#   homebrew: name={{item}} state=latest
#   with_items:
#     - shellcheck

- name: 'apm install : install atom packages'
  include_tasks: install-if-missing.yml
  vars:
    package_name: "{{ item }}"
  with_items:
    - TabNine
    - atom-beautify
    - atom-python-test
    - better-git-blame
    - busy-signal
    - highlight-selected
    - intentions
    - language-docker
    - language-groovy
    - language-jenkinsfile
    - language-terraform
    - linter
    - linter-pylint
    - linter-shellcheck
    - linter-terraform-semantics
    - linter-ui-default
    - minimap
    - minimap-highlight-selected
    - minimap-linter
    - pretty-json
    - python-black
    - python-debugger
    - sort-all-the-things
    - split-diff
    - terraform-lookup

- name: Check if Atom is running
  shell: ps -ef | grep atom | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: atom_process_result

- name: Copy config.cson to ~/.atom
  copy: src=config.cson dest=~/.atom backup=yes
  when: atom_process_result.rc != 0
