---
- name: Configure Dock
  osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  notify: killall Dock
  with_items:
    - domain: 'com.apple.dock'
      key: 'autohide'
      type: boolean
      value: true
    - domain: 'com.apple.dock'
      key: 'minimize-to-application'
      type: integer
      value: 0
    - domain: 'com.apple.dock'
      key: 'show-process-indicators'
      type: boolean
      value: true
    - domain: 'com.apple.dock'
      key: 'orientation'
      type: string
      value: bottom

    # top left screen corner — application windows
    - domain: 'com.apple.dock'
      key: 'wvous-tl-corner'
      type: integer
      value: 1
    - domain: 'com.apple.dock'
      key: 'wvous-tl-modifier'
      type: integer
      value: 0

    # top right screen corner — all windows (really Mission Control)
    - domain: 'com.apple.dock'
      key: 'wvous-tr-corner'
      type: integer
      value: 5
    - domain: 'com.apple.dock'
      key: 'wvous-tr-modifier'
      type: integer
      value: 0

    # bottom left screen corner — start screen saver
    - domain: 'com.apple.dock'
      key: 'wvous-bl-corner'
      type: integer
      value: 1
    - domain: 'com.apple.dock'
      key: 'wvous-bl-modifier'
      type: integer
      value: 0

    # bottom right screen corner — disable screen saver
    - domain: 'com.apple.dock'
      key: 'wvous-br-corner'
      type: integer
      value: 1
    - domain: 'com.apple.dock'
      key: 'wvous-br-modifier'
      type: integer
      value: 0

- osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  notify: killall cfprefsd
  with_items:
    # Needed to enable iterm2 session restore
    - domain: 'Apple Global Domain'
      key: 'NSQuitAlwaysKeepsWindows'
      type: boolean
      value: true

    - domain: 'Apple Global Domain'
      key: 'AppleInterfaceStyle'
      type: string
      value: Dark

    - domain: 'Apple Global Domain'
      key: 'com.apple.sound.uiaudio.enabled'
      type: int
      value: 0

    - domain: 'NSGlobalDomain'
      key: 'KeyRepeat'
      type: int
      value: 2

    - domain: 'NSGlobalDomain'
      key: 'InitialKeyRepeat'
      type: int
      value: 15

- osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  notify: killall SystemUIServer
  with_items:
    - domain: 'com.apple.menuextra.clock'
      key: 'DateFormat'
      type: string
      value: 'EEE d MMM  H:mm:ss'

- osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
  with_items:
    - domain: 'com.google.Chrome'
      key: 'AppleEnableSwipeNavigateWithScrolls'
      type: boolean
      value: false
    - domain: 'com.google.Chrome.canary'
      key: 'AppleEnableSwipeNavigateWithScrolls'
      type: boolean
      value: false
