  - osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
    notify: killall Dock
    with_items:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 0
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: bottom
  - osx_defaults: domain="{{ item.domain }}" key="{{ item.key }}" type="{{ item.type }}" value="{{ item.value }}" state=present
    with_items:
      # Needed to enable iterm2 session restore
      - domain: 'Apple Global Domain'
        key: 'NSQuitAlwaysKeepsWindows'
        type: boolean
        value: true
      - domain: 'Apple Global Domain'
        key: 'AppleInterfaceStyle'
        type: string
        value: Dark
