- name: "check if {{ package_name }} is installed"
  stat: path="~/.atom/packages/{{ package_name }}"
  register: package_folder

- name: "apm install {{ package_name }}"
  command: 'apm install {{ package_name }}'
  when: not package_folder.stat.exists
