---

- hosts: localhost
  connection: local
  vars:
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - caskroom/fonts
    homebrew_installed_packages:
      - awscli
      - brew-cask-completion
      - ffmpeg
      - fortune
      - git
      - id3v2
      - jq
      - openssh
      - python
      - python@2
      - ripgrep
      - the_silver_searcher
      - tmux
      - watch
      - zsh
    homebrew_cask_apps:
      - android-file-transfer
      - atom
      - font-fira-code
      - google-play-music-desktop-player
      - iterm2
      - music-manager
      - skitch
      - slack
      - spectacle
      - studio-3t
      - whatsapp
    folder_in_path: ~/bin
  pre_tasks:
    - import_role:
        name: ansible-role-homebrew
      tags: homebrew
    - name: create ~/bin
      file:
        path: "{{ folder_in_path }}"
        state: directory
    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^dresnick', line: 'dresnick ALL=(ALL) NOPASSWD: ALL' }
        - { regexp: '^Defaults    verifypw = any', line: 'Defaults    verifypw = any' }
    - name: add python 3 packages
      pip:
        executable: pip3
        name: virtualenv
    - name: add python 2 packages
      pip:
        executable: pip2
        name: virtualenv
    - name: Put link to pip2 in path
      file:
        src: "/usr/local/opt/python@2/bin/pip2"
        dest: "/Users/dresnick/bin/pip2"
        state: link

  roles:
    - { role: zsh, tags: zsh }
    - { role: osx-defaults, tags: osx-defaults }
    - { role: iterm2, tags: iterm2 }
    - { role: scheduled-pmset, tags: scheduled-pmset }
    - { role: various, tags: various }
    - { role: amazon-ecr-credential-helper, tags: amazon-ecr-credential-helper }
    - { role: atom-config, tags: atom-config }
    - { role: screensaver, tags: screensaver }
    - { role: ipython, tags: ipython }
    - { role: implisit-dev, tags: implisit-dev }
