---

- hosts: localhost
  connection: local

  tasks:
    - homebrew_tap:
        name: caskroom/fonts
    - name: install brew apps
      homebrew: name={{item}} state=latest
      with_items:
        # brew reinstall asciidoc --with-docbook-xsl
        # export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
        - lastpass-cli
        - brew-cask-completion
        - ffmpeg
        - git
        - id3v2
        - jq
        - the_silver_searcher
        - watch
        - zsh
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - atom
        - iterm2
        - font-fira-code
        - google-play-music-desktop-player
        - music-manager
        - skitch
        - slack
        - spectacle
        - studio-3t
        - whatsapp
    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^dresnick', line: 'dresnick ALL=(ALL) NOPASSWD: ALL' }
        - { regexp: '^Defaults    verifypw = any', line: 'Defaults    verifypw = any' }
    - name: Configure lastpass agent to never exit
      lineinfile: >
        dest=~/.lpass/env
        regexp='^LPASS_AGENT_TIMEOUT'
        line='LPASS_AGENT_TIMEOUT=0'
        state=present
        create=true
  roles:
    - osx-defaults
    - scheduled-pmset
    - { role: atom-config, tags: atom-config }
    - { role: screensaver, tags: screensaver }
    - { role: ipython, tags: ipython }
