---

- hosts: localhost
  connection: local

  tasks:
    - homebrew_tap:
        name: caskroom/fonts
    - name: install brew apps
      homebrew: name={{item}} state=latest
      with_items:
        - brew-cask-completion
        - ffmpeg
        - ripgrep
        - git
        - id3v2
        - jq
        - the_silver_searcher
        - watch
        - zsh
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - android-file-transfer
        - atom
        - iterm2
        - font-fira-code
        - google-play-music-desktop-player
        - music-manager
        - skitch
        - slack
        - spectacle
        - studio-3t
        - whatsapp
    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^dresnick', line: 'dresnick ALL=(ALL) NOPASSWD: ALL' }
        - { regexp: '^Defaults    verifypw = any', line: 'Defaults    verifypw = any' }
  roles:
    - { role: zsh, tags: zsh }
    - { role: osx-defaults, tags: osx-defaults }
    - { role: scheduled-pmset, tags: scheduled-pmset }
    - { role: various, tags: various }
    - { role: amazon-ecr-credential-helper, tags: amazon-ecr-credential-helper }
    - { role: atom-config, tags: atom-config }
    - { role: screensaver, tags: screensaver }
    - { role: ipython, tags: ipython }
    - { role: implisit-dev, tags: implisit-dev }
