---

- hosts: localhost
  connection: local

  tasks:
    - homebrew_tap:
        name: caskroom/fonts       
    - name: install brew apps
      homebrew: name={{item}} state=latest
      with_items:
        - brew-cask-completion
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - spectacle
