---

- hosts: localhost
  connection: local
  vars:
    homebrew_taps:
      - github/gh
      - hashicorp/tap
      - homebrew/cask
      - homebrew/cask-fonts
      - homebrew/core
      - homebrew/services
      - kudulab/dojo-osx
      # - rhyeal/aws-rotate-iam-keys
      # - salesforce/policy_sentry
    homebrew_installed_packages:
      - asciidoc
      - autossh
      # - rhyeal/aws-rotate-iam-keys/aws-rotate-iam-keys
      - bash
      - brew-cask-completion
      - dos2unix
      - folly
      - fortune
      - fswatch
      - fzf
      - gh
      - git
      - git-delta
      - git-gui
      - gradle
      - graphviz
      - grep
      - helm
      - highlight
      - id3v2
      - jq
      - iproute2mac
      - kubectx
      - lastpass-cli
      - maven
      - oath-toolkit
      - opencv
      - openssh
      # - salesforce/policy_sentry/policy_sentry
      - pstree
      - pyenv-virtualenv
      - ripgrep
      - shellcheck
      - socat
      - telnet
      - terraform
      - tflint
      - the_silver_searcher
      - tmux
      - tree
      - watch
      - wget
      - youtube-dl
      - yq
      - zlib
      - zsh
    homebrew_cask_apps:
      - aerial
      - android-file-transfer
      - atom
      - balance-lock
      - balenaetcher
      - daisydisk
      - disk-inventory-x
      - docker
      - font-fira-code
      - gpg-suite-no-mail
      - iterm2
      - lastpass
      - marshallofsound-google-play-music-player
      - meld
      - music-manager
      - musicbrainz-picard
      - pluralsight
      - postman
      - pycharm
      - rectangle
      - skitch
      - slack
      - sloth
      - spectacle
      - studio-3t
      - sweet-home3d
      - visual-studio-code
      - vlc
      - whatsapp
    folder_in_path: ~/bin
  pre_tasks:
    - import_role:
        name: ansible-role-homebrew
      tags: homebrew
    - name: create ~/bin
      file:
        path: "{{ folder_in_path }}"
        state: directory
    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^dresnick', line: 'dresnick ALL=(ALL) NOPASSWD: ALL' }
        - { regexp: '^Defaults    verifypw = any', line: 'Defaults    verifypw = any' }

  roles:
    - { role: zsh, tags: zsh }
    - { role: osx-defaults, tags: osx-defaults }
    - { role: iterm2, tags: iterm2 }
    # - { role: scheduled-pmset, tags: scheduled-pmset }
    - { role: python, tags: python }
    - { role: various, tags: various }
    # - { role: amazon-ecr-credential-helper, tags: amazon-ecr-credential-helper }
    - { role: atom-config, tags: atom-config }
    # - { role: screensaver, tags: screensaver }
    # - { role: minikube, tags: minikube }
    # - { role: superlumic-role-implisit-dev, tags: implisit-dev }
