---

- name: install pyenv
  include_role:
    name: markosamuli.pyenv
  vars:
    pyenv_python36_version: "3.6.11"
    pyenv_global: "{{ pyenv_python36_version }}"

- name: add python 3 packages
  pip:
    executable: pip3
    name:
      - instagram-scraper

- name: "ipython: Ensure default profile folder exists"
  file:
    path: ~/.ipython/profile_default
    state: directory

- name: "ipython: Copy ipython config to default profile"
  copy:
    src: ipython_config.py
    dest: ~/.ipython/profile_default
