---

# installed from central list
# - name: install zsh
#   homebrew:
#     name: zsh
#     state: latest
- name: get fork of zprezto
  git:
    repo: "{{ zprezto_repo_url }}"
    accept_hostkey: yes
    recursive: yes
    dest: "{{ zprezto_dir }}"

- name: update zprezto repo - git remote set-url origin
  tags: git
  command: "git remote set-url origin git@github.com:dresnick-sf/prezto"
  args:
    chdir: "{{ zprezto_dir }}"

- name: update zprezto repo - git remote add upstream
  tags: git
  command: "git remote add upstream https://github.com/sorin-ionescu/prezto.git"
  register: gitresult
  args:
    chdir: "{{ zprezto_dir }}"
  failed_when: "gitresult.rc != 0 and gitresult.stderr != 'fatal: remote upstream already exists.'"

- name: create links to zsh rcfiles
  file:
    src: "{{ zprezto_dir }}/runcoms/{{ item }}"
    dest: "{{ zdotdir }}/.{{ item }}"
    state: link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
- name: set current shell to zsh
  become: yes
  command: "dscl . -create /Users/{{ ansible_user }} UserShell /usr/local/bin/zsh"
  register: dscl
- debug: var=dscl
- name: check for insecure directories in the zsh fpath
  command: /usr/local/bin/zsh -c 'source /usr/local/share/zsh/functions/compaudit'
  register: compaudit
  ignore_errors: yes
  changed_when: no
- debug: var=compaudit
- name: Fix compaudit errors
  file:
    path: "{{ item }}"
    mode: "g-w"
    owner: "{{ ansible_user }}"
    group: "admin"
  with_items: "{{ compaudit.stdout_lines }}"
