---

- name: install and configure fzf
  include_tasks: fzf.yml
  tags: fzf
- name: copy gitconfig
  tags: git
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
    backup: yes
- name: create ~/src/proj
  tags: git
  file:
    path: ~/src/proj
    state: directory

- name: get various-scripts
  tags: git
  git:
    repo: 'git@github.com:david-resnick/various-scripts.git'
    dest: ~/src/proj/various-scripts
- name: set abunetta email for various-scripts repo
  tags: git
  command: git config user.email "abunetta@gmail.com"
  args:
    chdir: ~/src/proj/various-scripts
- name: set abunetta key for various-scripts repo
  tags: git
  command: git config core.sshCommand "ssh -i ~/.ssh/abunetta.pem -F /dev/null"
  args:
    chdir: ~/src/proj/various-scripts
- name: add links for scripts
  tags: git
  file:
      src: "{{ item }}"
      dest: "~/bin/{{ item | basename }}"
      state: link
  loop: "{{ lookup('fileglob', '~/src/proj/various-scripts/*', wantlist=True) }}"

- name: update superlumic-config repo - git remote set-url origin
  tags: git
  command: "git remote set-url origin git@github.com:dresnick-sf/superlumic-config"
  args:
    chdir: /usr/local/superlumic/config

- name: update superlumic-config repo - git remote add upstream
  tags: git
  command: "git remote add upstream https://github.com/superlumic/superlumic-config.git"
  register: gitresult
  args:
    chdir: /usr/local/superlumic/config
  failed_when: "gitresult.rc != 0 and gitresult.stderr != 'fatal: remote upstream already exists.'"
